swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /targets:
    get:
      operationId: "netprobify.dynamic_inventories.api.get_targets"
      tags:
        - "Targets"
      summary: "Read of on the go targets list"
      parameters:
        - name: hostname
          in: query
          type: string
          description: Hostname of the target to filter
        - name: owner
          in: query
          type: string
          description: Hostname of the target to filter
      responses:
        200:
          description: "Successful read targets list operation"
      security:
        - basic: []
  /target:
    post:
      operationId: "netprobify.dynamic_inventories.api.add_target"
      tags:
        - "Target"
      summary: "Add on the go targets"
      consumes:
        - application/json
      parameters:
        - in: body
          name: target
          schema:
            type: object
            required:
              - hostname
              - owner
            properties:
              owner:
                type: string
                description: Owner of the target
              hostname:
                type: string
                description: Hostname of the target to add
              type:
                type: string
                description: Probing type of the target
              dst_port:
                type: integer
                description: Destination port of the target
              ip_payload_size:
                type: integer
                description: IP payload size
              lifetime:
                type: string
                description: Lifetime of the target ("1d 1h 1m" for example)
      responses:
        201:
          description: "Successful targets addition"
          schema:
            type: array
            items:
              properties:
                result:
                  type: string
      security:
        - basic: []

    delete:
      operationId: "netprobify.dynamic_inventories.api.remove_target"
      tags:
        - Target
      consumes:
        - application/json
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - in: body
          name: target
          schema:
            type: object
            required:
              - hostname
              - owner
            properties:
              owner:
                type: string
                description: Owner of the target
              hostname:
                type: string
                description: Hostname of the target to add
              type:
                type: string
                description: Probing type of the target
              dst_port:
                type: integer
                description: Destination port of the target
              ip_payload_size:
                type: integer
                description: IP payload size
      responses:
        200:
          description: Successfully deleted a person from people list
      security:
        - basic: []

securityDefinitions:
  basic:
    type: apiKey
    in: header
    name: apikey
    x-apikeyInfoFunc: "netprobify.dynamic_inventories.api.auth_token"